# Generated by Django 5.1.4 on 2024-12-29 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('published_date', models.DateField()),
                ('category', models.TextField()),
                ('available_copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('membership_date', models.DateField()),
                ('membership_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.members')),
            ],
        ),
    ]
